language:
  - objective-c

env:
  matrix:
    - VERSION="2.7.12"
    - VERSION="3.4.4"
    - VERSION="3.5.2"
    - VERSION="3.6.0a3"

install:
  - set -vx  # echo commands
  - git submodule update --init
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install wheel nose
  - python setup.py install

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - nosetests delocate
