language:
  - objective-c

env:
  matrix:
    - VERSION="2.7.7"
    - VERSION=3.2.5
    - VERSION="3.3.5"
    - VERSION="3.4.1"

install:
  - set -vx  # echo commands
  - git submodule update --init
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install wheel nose
  - python setup.py install

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - nosetests delocate
