language:
  - objective-c

env:
  global:
    - VERSION="3.5.2"

# Default OSX (xcode image) is 10.10 (xcode 7.3) as of 2016-11-23

matrix:
  include:
      - env: VERSION="2.7.12"
      - env: VERSION="3.4.4"
      - env: VERSION="3.5.2"
      - env: VERSION="3.6.0b4"
      # OSX 10.9
      - osx_image: beta-xcode6.1
      # OSX 10.10
      - osx_image: xcode6.4
      # OSX 10.12
      - osx_image: xcode8.2

install:
  - set -vx  # echo commands
  - source multibuild/osx_utils.sh
  - get_macpython_environment $VERSION venv
  - pip install wheel nose
  - python setup.py install

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - nosetests delocate
